version: '3.7'

services:
# Build the app services
  app:
    build: app
  frontend:
    build: frontend
    volumes:
      - ./frontend/src/.:/app/src/.
  nginx:
    container_name: nginx
    build: nginx
    # Bind port 80 of container to machine port 80
    ports:
      - 80:80
    # Make app as ngnix dependency service
    #depends_on:
    #  - app
    #  - frontend